<script>
    if(typeof window.HelloChat == 'undefined'){
        window.HelloChat = {};
    }

    window.HelloChat.general = {
    'localization' : {
        'color' : {
            'title' : 'Kleuren',
            'main' : 'Primaire',
            'mainColor' : 'Kleur',
            'primaryShade' : 'Accentkleur',
            'secondary' : 'Secundaire',
            'secondaryColor' : 'Kleur',
            'secondaryShade' : 'Accentkleur',
            'ui' : 'User Interface',
            'uiText' : 'Tekst'
        },
        'text' : {
            'initial' : 'Openingsbericht',
            'initialMessage' : 'Openingsbericht inhoud',
            'initialName' : 'Openingsbericht afzender naame',
            'initialEmail' : 'Openingsbericht afzender email',
            'title' : 'Teksten',
            'header' : 'Header',
            'chatPlaceholder' : 'Chatnaam placeholder',
            'welcome' : 'Inleiding',
            'introTitle' : 'Inleidingstekst titel',
            'introDescription' : 'Inleidingstekst omschrijving',
            'formName' : 'Inleiding naam placeholder',
            'formEmail' : 'Inleiding naam placeholder',
            'formPrivacy' : 'Privacy label <small>([url][/url] om een link te plaatsen)</small>',
            'formPrivacyUrl' : 'URL naar de privacy pagina',
            'formSubmit' : 'Formulier verstuur tekst',
            'chat' : 'Chat',
            'chatClose' : 'Chat sluiten',
            'chatOverview' : 'Chatoverzicht menuknop',
            'chatMessage' : 'Chat input veld placeholder',
            'chatNotification' : 'Titel van browser notificatie',
            'connect' : 'Verbinden',
            'connectButton' : 'Knop tekst: chat verbinden',
            'users' : 'Gebruikers',
            'userTitle' : 'Chat overzicht titel',
            'userButton' : 'Chat claim tekst',    
            'userActive' : 'Chat overzicht titel: niet geclaimed',
            'userInactive' : 'Chat overzicht titel: geclaimed',
            'userJoin' : 'Deelnemen aan chat knop',
            'archive' : 'Archief',
            'archiveTitle' : 'Archief titel',
            'archiveButton' : 'Archief bekijk gebruiker titel',
            'archiveRefresh' : 'Vernieuwen menuknop',
            'archiveUsers' : 'Chats',
            'archiveFilter' : 'Filter label',
            'archiveFilterDefault' : 'Standaard filter optie',
            'detail' : 'Gebruiker Detail',
            'detailMail' : 'Mail button tekst',
            'detailConversation' : 'Gespreksoverzicht titel',
            'detailRemove' : 'Chat verwijderen menuknop',
            'detailArchive' : 'Archief menuknop',
            'confirmation' : 'Bevestiging',
            'confirmationMessage' : 'Bevestigingstekst',
            'confirmationYes' : 'Akoord knop',
            'confirmationNo' : 'Afwijzen knop',
            'settings' : 'Instellingen',
            'settingsTitle' : 'Instellingen titel',
            'settingsMenu' : 'Instellingen menuknop',
            'system' : 'Systeem Instellingen',
            'systemPassword' : 'Cronjob Wachtwoord',
            'inactiveDescription' : 'Chat inactief omschrijving',
            'inactiveButton' : 'Neem contact op',
            'inactiveUrl' : 'Chat inactief URL',
            'activateLabel' : 'Activeer chat label',
            'end' : 'Eindscherm',
            'endTitle' : 'Eindscherm titel',
            'endDescription' : 'Eindscherm tekst',
        }
    }
}
</script>